Sscs 10292
hmcts/sscs-common pull request #1293
Opened 2022-09-06 14:33 UTC by hgulv1

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/SSCS-10292

### Change description ###
As a Judge
I want the hearing format selected in the adjournment notice to be used for the subsequent hearing request
So that the new hearing is created with the correct format

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

2022-09-07 15:51 UTC, mcareyma commented
This seems good, but how will it work with other repositories to give you what we need.

2022-09-08 09:01 UTC, hgulv1 commented
> This seems good, but how will it work with other repositories to give you what we need.

The next step is to use it in Hearings API where the Hearing Channel is requested and return the value.

2022-09-08 10:51 UTC, amoslv1 approved these changes

2022-09-08 13:19 UTC, TeaWithLucas approved these changes

2022-09-15 09:05 UTC, dattipoeHMCTS requested changes

2022-09-15 09:05 UTC, dattipoeHMCTS commented on src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
> +    private HearingChannel adjournCaseTypeOfNextHearing;
You can't just change this type, it's already in use in different parts of the system. You need to resolve the hearing channel from the string

2022-09-21 13:36 UTC, closed without merging