SSCS-10756 adds correction request to DocumentType and ScannedDocumentType
hmcts/sscs-common pull request #1426
Opened 2023-03-01 09:08 UTC by amoslv1

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/SSCS-10576

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2023-03-02 10:36 UTC, amoslv1 commented on src/main/java/uk/gov/hmcts/reform/sscs/ccd/callback/DocumentType.java
> +    CORRECTION_APPLICATION("correctionApplication", "Correction application"),
new

2023-03-02 10:36 UTC, amoslv1 commented on src/main/java/uk/gov/hmcts/reform/sscs/ccd/callback/ScannedDocumentType.java
> +    CORRECTION_APPLICATION("correctionApplication", "Correction application"),
new

2023-03-07 14:29 UTC, AndreiTrushkov approved these changes

2023-03-09 09:38 UTC, StevensonSi approved these changes

2023-03-09 09:42 UTC, nickhill111 requested changes

2023-03-09 09:42 UTC, nickhill111 commented on config/owasp/suppressions.xml
> +    <cve>CVE-2022-45688</cve>
this suppression already exists on line 11

2023-03-09 09:42 UTC, nickhill111 commented on config/owasp/suppressions.xml
> +    <cve>CVE-2023-24998</cve>
same with this one for line 4 (but might be better to delete the one on line 4

2023-03-09 10:02 UTC, amoslv1 commented on config/owasp/suppressions.xml
> +    <cve>CVE-2023-24998</cve>
good spots - removed

2023-03-09 10:02 UTC, amoslv1 commented on config/owasp/suppressions.xml
> +    <cve>CVE-2022-45688</cve>
removed

2023-04-14 07:40 UTC, closed without merging

2023-04-14 07:40 UTC, amoslv1 commented
Required changes already merged from SSCS-10984