Court rename
hmcts/sscs-common pull request #1540
Opened 2023-11-02 09:16 UTC by AndreiTrushkov

### Jira link (if applicable)
https://tools.hmcts.net/jira/browse/SSCS-12069

### Change description ###
Court rename

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2023-11-07 15:28 UTC, nickhill111 approved these changes

2023-11-08 09:33 UTC, DGordonV1 approved these changes

2023-11-08 09:35 UTC, DGordonV1 requested changes
Is this the correct name? Doesn't look right.

2023-11-08 10:59 UTC, DGordonV1 approved these changes

2023-12-12 10:43 UTC, nickhill111 approved these changes

2023-12-12 10:46 UTC, merged