Changed logic of how full name of judicial user is generated
hmcts/sscs-common pull request #1554
Opened 2024-01-25 11:47 UTC by AndreiTrushkov

checkstyle fixes

### Jira link (if applicable)
https://tools.hmcts.net/jira/browse/SSCS-12116

### Change description ###
Changed logic of how full name of judicial user is generated

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-01-25 15:03 UTC, nickhill111 requested changes

2024-01-29 09:49 UTC, nickhill111 approved these changes

2024-01-29 11:20 UTC, markbrooks725 approved these changes

2024-01-29 11:21 UTC, AndreiTrushkov commented on src/main/java/uk/gov/hmcts/reform/sscs/service/JudicialRefDataService.java
> +        return String.format("%s %s %s", judicialUser.getTitle(), judicialUser.getInitials(), judicialUser.getSurname());
Resolved

2024-02-07 09:53 UTC, DGordonV1 approved these changes

2024-02-07 09:59 UTC, merged