SSCSCI-759: Filter null hearingOptions
hmcts/sscs-common pull request #1582
Opened 2024-04-02 14:16 UTC by hashimalisolirius

### Jira link (if applicable)

https://tools.hmcts.net/jira/browse/SSCSCI-759

### Change description ###
Add null check before checking if interpreter is required

2024-05-23 14:34 UTC, KatKovacs1 approved these changes

2024-05-23 14:41 UTC, sanjayparekh-hmcts requested changes

2024-05-23 14:41 UTC, sanjayparekh-hmcts commented on src/test/java/uk/gov/hmcts/reform/sscs/utility/HearingChannelUtilTest.java
> +    void testNullHearingOptionsOtherParty(){
you should probably put a non-null test in too

2024-05-24 11:32 UTC, sanjayparekh-hmcts approved these changes

2024-05-24 12:33 UTC, NHAL22 approved these changes

2024-05-24 13:20 UTC, benouaer approved these changes

2024-06-25 09:54 UTC, merged