SSCSSI-336: Overloaded handleCcdCallbackMapV2 to take in handler mutator
hmcts/sscs-common pull request #1620
Opened 2024-07-08 16:52 UTC by SomeshRA

### Jira link (if applicable)
https://tools.hmcts.net/jira/browse/SSCSSI-336

### Change description ###
Overloaded handleCcdCallbackMapV2 to take in handler mutator

### Checklist

- [ X] commit messages are meaningful and follow good commit message guidelines
- [ X] tests have been updated / new tests has been added (if needed)

2024-07-11 08:40 UTC, sanjayparekh-hmcts requested changes

2024-07-11 08:40 UTC, sanjayparekh-hmcts commented on src/test/java/uk/gov/hmcts/reform/sscs/ccd/service/CcdCallbackMapServiceTest.java
> +                .updateCaseV2(eq(CASE_ID), eq(EventType.READY_TO_LIST.getCcdType()), eq("summary"), eq("description"), eq(idamTokens), any(Consumer.class)))
Might be worth cleaning up the static imports for event type in this class
Also any blank spaces/tabs introduced if thats appropriate

2024-08-27 10:03 UTC, sanjayparekh-hmcts approved these changes

2024-09-02 09:50 UTC, srochani approved these changes

2024-09-02 09:54 UTC, merged